# Generated by Django 4.2.4 on 2023-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_uav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('cat1', 'CATEGORY-1'), ('cat2', 'CATEGORY-2'), ('cat3', 'CATEGORY-3')], default='cat1', max_length=12),
        ),
    ]
